title: r9y.dev capability details
remote_theme: mmistakes/minimal-mistakes

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

analytics:
  provider: google
  google:
    tracking_id: G-DLHPSNJ96L